### ISSUE TITLE
Language changing

### ISSUE THREAD

**Issue by ionymikler** [darwiin/yaac-another-awesome-cv#10]
Hi Christoph!
I really liked your template, However, I'm having a hard time changing the language from french to spanish. I changed the babel parameters, but I get the following message:
![captura](https://user-images.githubusercontent.com/38387236/42138556-a12d0b16-7d44-11e8-8502-604ce29775c6.JPG)
How should I proceed?
Additionally, I find the language level points depiction very creative, do you think is possible to add the option to have half circles? like for example if someone feels he neither a 3 nor a 4 in _Arabic_ but something in between

**Comment by darwiin** [comment]
Hi,
How did you do this. I just change the language settings in the cls file to spanish and have no problem to build the cv.

For the language section, I am using font awesome icons and unfortunately there is no half circle icons...

**Comment by michelmotta** [comment]
I was having this issue. This is because I have deleted the words english and french from: `\RequirePackage[english,french]{babel}` and I was trying to keept it like: `\RequirePackage[portuguese]{babel}`. My way to fix it was to add the portuguese after the word french `\RequirePackage[english,french,portuguese]{babel}`. I'm not sure if this is the right way to do it, but fixed the problem.

@darwiin awesome work!! This is really cool and professional template.

**Comment by darwiin** [comment]
Last comment was posted 12 days ago, I close this issue.
